### ISSUE TITLE
xlua  **.lua.txt中断点无法触发

### ISSUE THREAD

**Issue by septbr** [qweyouke/XXLua-for-VSCode#2]
unity项目lua使用的是**.lua.txt后缀

**Comment by qweyouke** [comment]
@septbr 项目平时开发不是.lua.txt后缀吧。 真机出的问题？

**Comment by septbr** [comment]
> 
一直都是.lua.txt后缀，不是真机，就正常的unityeditor+vscode环境

**Comment by qweyouke** [comment]
运行格式不重要，但是至少需要在vscode中是.lua格式的。
